-- CreateTable
CREATE TABLE `ExhibitionExpenses` (
    `id` CHAR(36) NOT NULL,
    `category` ENUM('RENT', 'UTILITIES', 'SALARIES', 'SUPPLIES', 'MAINTENANCE', 'TRANSPORT', 'INSURANCE', 'MARKETING', 'TRAINING', 'TAXES', 'MEDICAL_SUPPLIES', 'OFFICE_SUPPLIES', 'EQUIPMENT_PURCHASE', 'EQUIPMENT_REPAIR', 'CLEANING', 'SECURITY', 'INTERNET', 'WATER', 'ELECTRICITY', 'COMMUNICATION', 'SOFTWARE_SUBSCRIPTIONS', 'MISCELLANEOUS') NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NULL,
    `amount` DOUBLE NOT NULL,
    `dateIncurred` DATETIME(3) NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
