export const unitsOfMeasurement = [
  // 🔹 General Units
  { name: 'Piece', abr: 'pc' },
  { name: 'Dozen', abr: 'dz' },
  { name: 'Pair', abr: 'pr' },
  { name: 'Pack', abr: 'pk' },
  { name: 'Box', abr: 'bx' },
  { name: 'Bottle', abr: 'btl' },
  { name: 'Bag', abr: 'bag' },
  { name: 'Carton', abr: 'ctn' },
  { name: 'Sachet', abr: 'sct' },
  { name: 'Roll', abr: 'roll' },
  { name: 'Bundle', abr: 'bdl' },

  // 🔹 Weight-based units
  { name: 'Kilogram', abr: 'kg' },
  { name: 'Gram', abr: 'g' },
  { name: 'Milligram', abr: 'mg' },
  { name: 'Tonne', abr: 't' },

  // 🔹 Volume-based units
  { name: 'Litre', abr: 'L' },
  { name: 'Millilitre', abr: 'ml' },
  { name: 'Cubic Meter', abr: 'm³' },
  { name: 'Cubic Centimeter', abr: 'cm³' },

  // 🔹 Length-based units
  { name: 'Meter', abr: 'm' },
  { name: 'Centimeter', abr: 'cm' },
  { name: 'Millimeter', abr: 'mm' },
  { name: 'Kilometer', abr: 'km' },
  { name: 'Inch', abr: 'in' },
  { name: 'Foot', abr: 'ft' },
  { name: 'Yard', abr: 'yd' },
  { name: 'Mile', abr: 'mi' },

  // 🔹 Predefined Package Weights (Grams)
  { name: '10 Grams', abr: '10g' },
  { name: '20 Grams', abr: '20g' },
  { name: '30 Grams', abr: '30g' },
  { name: '40 Grams', abr: '40g' },
  { name: '50 Grams', abr: '50g' },
  { name: '60 Grams', abr: '60g' },
  { name: '70 Grams', abr: '70g' },
  { name: '80 Grams', abr: '80g' },
  { name: '90 Grams', abr: '90g' },
  { name: '100 Grams', abr: '100g' },
  { name: '120 Grams', abr: '120g' },
  { name: '150 Grams', abr: '150g' },
  { name: '180 Grams', abr: '180g' },
  { name: '200 Grams', abr: '200g' },
  { name: '250 Grams', abr: '250g' },
  { name: '300 Grams', abr: '300g' },
  { name: '400 Grams', abr: '400g' },
  { name: '500 Grams', abr: '500g' },
  { name: '750 Grams', abr: '750g' },
  { name: '1 Kilogram', abr: '1kg' },
  { name: '2 Kilograms', abr: '2kg' },
  { name: '5 Kilograms', abr: '5kg' },
  { name: '10 Kilograms', abr: '10kg' },
  { name: '25 Kilograms', abr: '25kg' },
  { name: '50 Kilograms', abr: '50kg' },

  // 🔹 Predefined Package Volumes (Millilitres & Litres)
  { name: '10 Millilitres', abr: '10ml' },
  { name: '20 Millilitres', abr: '20ml' },
  { name: '30 Millilitres', abr: '30ml' },
  { name: '40 Millilitres', abr: '40ml' },
  { name: '50 Millilitres', abr: '50ml' },
  { name: '60 Millilitres', abr: '60ml' },
  { name: '70 Millilitres', abr: '70ml' },
  { name: '80 Millilitres', abr: '80ml' },
  { name: '90 Millilitres', abr: '90ml' },
  { name: '100 Millilitres', abr: '100ml' },
  { name: '120 Millilitres', abr: '120ml' },
  { name: '150 Millilitres', abr: '150ml' },
  { name: '180 Millilitres', abr: '180ml' },
  { name: '200 Millilitres', abr: '200ml' },
  { name: '250 Millilitres', abr: '250ml' },
  { name: '300 Millilitres', abr: '300ml' },
  { name: '350 Millilitres', abr: '350ml' },
  { name: '400 Millilitres', abr: '400ml' },
  { name: '450 Millilitres', abr: '450ml' },
  { name: '500 Millilitres', abr: '500ml' },
  { name: '600 Millilitres', abr: '600ml' },
  { name: '700 Millilitres', abr: '700ml' },
  { name: '750 Millilitres', abr: '750ml' },
  { name: '800 Millilitres', abr: '800ml' },
  { name: '900 Millilitres', abr: '900ml' },
  { name: '1 Litre', abr: '1L' },
  { name: '1.5 Litres', abr: '1.5L' },
  { name: '2 Litres', abr: '2L' },
  { name: '3 Litres', abr: '3L' },
  { name: '5 Litres', abr: '5L' },
  { name: '10 Litres', abr: '10L' },
  { name: '20 Litres', abr: '20L' },
  { name: '25 Litres', abr: '25L' },
];
